---
- name: Verify
  hosts: all

  tasks:
    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
